script: |
  cd ~
  if [ ! -d "docker-project" ]; then
    git clone https://github.com/Mfaiz01/MyPortfolio.git docker-project
  fi
  cd docker-project
  git pull origin main
  docker build -t my-portfolio .
  docker stop portfolio || true
  docker rm portfolio || true
  docker run -d -p 80:80 --name portfolio --restart always my-portfolio
